### ISSUE TITLE
About 'ProcessOptionsLinkParent'

### ISSUE THREAD

**Issue by Capybara-1** [ergo-services/ergo#191] opened 2024-10-16 17:55 UTC
**Describe the bug**

When the Supervisor-Actor's Spawan Child Actor Options.LinkParent is set to true,

if the Child Actor  exits before the Supervisor-Actor, the Supervisor will hang for about 30 seconds during Node.Stop.

![image](https://github.com/user-attachments/assets/11e175e3-5a98-45a5-82ba-41aa23d6a018)

**Comment by halturin** [comment] 2024-10-16 18:52
please, provide an example that reproduces this behaviour.

PS your code looks so weird. can you pls share the source of your Actor?

**Comment by DustOak** [comment] 2024-10-17 11:53
> please, provide an example that reproduces this behaviour.
> 
> PS your code looks so weird. can you pls share the source of your Actor?

I apologize that due to confidentiality regulations, I cannot show you too much code. The code looks strange because we have done a secondary encapsulation for Ergo 3.0. The encapsulation is a light one and does not change the original function behavior.

The general process we encountered for this issue is as follows:

1. Use application to start a supervisor and run a websocket management Actor inside it. This management Actor will start a meta for ServerListener.
2. When a new websocket connection is established, I use this manager's Actor to SpawnMeta and start a meta for sending and receiving.
3. At the same time, a standard sub-ProcessBehavior is launched to process the information received from the read-write meta and return. The start parameter LinkParent is set to true.
4. My manager monitors the above Actor and Meta.
5. From now on, problems arise.
6. When I disconnect the websocket or the sub-ProcessBehavior exits, it will notify the manager and then exit another one.
7. However, when I use Node.Stop, the supervisor cannot exit, and the entire process will end after about 1-2 minutes.


**Thank you very much for your reply. I am not sure why this is happening; perhaps I made a mistake or used it improperly. I apologize for any trouble this may have caused you.**

**Comment by halturin** [comment] 2024-10-17 12:23
thank you for sharing details. but still, without seeing a code, it is difficult to understand and help you to solve this issue.

what was the reason of that encapsulation?

why dont you use WebSocket from https://github.com/ergo-services/meta? example can be found here https://github.com/ergo-services/examples (see websocket).

>about 1-2 minutes

gen.Node.Stop() waits all process to be terminated. see https://docs.ergo.services/basics/node#node-shutdown

seems your process is stuck, because of socket is being in TIME_WAIT state until kernel close it forcibly.

**Closed** 2024-10-19 06:30 UTC
